import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";

// ✅ Load Outfit font
const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

// ✅ Metadata
export const metadata: Metadata = {
  title: "Stack Decode CRM",
  description: "Generated by create next app",
};

// ✅ Root Layout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} antialiased`}>
        <main>{children}</main>
      </body>
    </html>
  );
}
